apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: jarek1725/systemy-gridowe-application:latest
          ports:
            - containerPort: 80
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db-service:5432/projektSystemyGridowe
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: admin
            - name: SERVER_PORT
              value: "8080"
            - name: SERVER_ADDRESS
              value: "0.0.0.0"
